swagger: "2.0"
info:
  description: "This is a simple trademark search server for trademarks registered in Europe. You can use this to check for existing trademarks with the provided endpoints/resources."
  version: "1.0.0"
  title: "Europe trademark search"
  contact:
    email: "samueldubcak@gmail.com"
host: "localhost:5000"
basePath: "/v1"
tags:
- name: "trademark"
  description: "Existing trademark as registered in Europe"
schemes:
- "http"

paths:
  /trademark/byExactName:
    get:
      tags:
      - "trademark"
      summary: "Returns a simplified trademark object based on it's exact name"
      description: ""
      operationId: "handler.getByExactName"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "name"
        in: "query"
        description: "Exact name to search trademarks by"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
              $ref: "#/definitions/Trademark"
        "400":
          description: "Trademark not found"
  /trademark/byApproximateName:
    get:
      tags:
      - "trademark"
      summary: "Returns an array of simplified trademark objects based on their approximate search name"
      description: ""
      operationId: "handler.getByApproximateName"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "name"
        in: "query"
        description: "Approximate name to search trademarks by"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/TrademarkArray"
        "400":
          description: "No trademarks found"

definitions:
  Trademark:
    type: "object"
    properties:
      MarkFeature:
        type: "string"
        example: "Word"
      WordMarkSpecification:
        type: "string"
        example: "NOMAD"
      MarkCurrentStatusCode:
        type: "string"
        example: "Registered"
      ApplicationDate:
        type: "string"
        example: "2001-01-04"
      RegistrationDate:
        type: "string"
        example: "2002-07-10"
      ExpiryDate:
        type: "string"
        example: "2021-01-04"
    xml:
      name: "Trademark"
  TrademarkArray:
    type: "array"
    xml:
      name: "trademark"
    items: 
      $ref: "#/definitions/Trademark"
