swagger: "2.0"
info:
  description: "This is a simple trademark search api for trademarks registered in EU. You can use the provided endpoints/resources to check for existing trademarks."
  version: "1.0.0"
  title: "EU trademark search"
  contact:
    email: "deagllle@gmail.com"
host: "localhost:5000"
basePath: "/v1"
tags:
- name: "trademark"
  description: "Existing trademark"
schemes:
- "http"

paths:
  /trademark/byExactName:
    get:
      tags:
      - "trademark"
      summary: "Returns an array of simplified trademark objects based on their exact name"
      description: ""
      operationId: "handler.get_by_exact_name"
      produces:
      - "application/xml"
      parameters:
      - name: "name"
        in: "query"
        description: "Exact name to search trademarks by"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
              $ref: "#/definitions/Trademark"
        "400":
          description: "Trademark not found"
  /trademark/byApproximateName:
    get:
      tags:
      - "trademark"
      summary: "Returns an array of simplified trademark objects based on their approximate name"
      description: ""
      operationId: "handler.get_by_approx_name"
      produces:
      - "application/xml"
      parameters:
      - name: "name"
        in: "query"
        description: "Approximate name to search trademarks by"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/TrademarkArray"
        "400":
          description: "No trademarks found"

definitions:
  Trademark:
    type: "object"
    properties:
      ApplicationDate:
        type: "string"
        example: "2001-01-04"
      ApplicationLanguageCode:
        type: "string"
        example: "en"
      SecondLanguageCode:
        type: "string"
        example: "fr"
      MarkFeature:
        type: "string"
        example: "Word"
      MarkVerbalElementText:
        type: "string"
        example: "VERIFAI"
    xml:
      name: "Trademark"
  TrademarkArray:
    type: "array"
    xml:
      name: "trademark"
    items: 
      $ref: "#/definitions/Trademark"
